"""Synthetic recovery diagnostics for the v3 team-state implementation.

This module is intentionally diagnostic, not a production fitter. It creates a
known linear-Gaussian offense/defense state-space history and then evaluates or
fits the same within-season parameters used by ``GaussianOffenseDefenseFilter``.

The purpose is to catch implementation/identification errors before NFL
hyperparameter estimation: if known persistence, process noise, and observation
noise cannot be recovered from synthetic data generated by the assumed model,
real-data estimates are not interpretable.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from math import log, pi
from typing import Sequence

import numpy as np
from scipy.optimize import minimize

from .team_state import GaussianOffenseDefenseFilter, StateSpaceConfig


@dataclass(frozen=True)
class SyntheticWeek:
    offenses: tuple[str, ...]
    defenses: tuple[str, ...]
    observations: np.ndarray

    def __post_init__(self) -> None:
        if len(self.offenses) != len(self.defenses) or len(self.offenses) != len(self.observations):
            raise ValueError("synthetic observation arrays must have equal length")
        if len(self.observations) == 0:
            raise ValueError("synthetic week must contain observations")
        if not np.isfinite(self.observations).all():
            raise ValueError("synthetic observations must be finite")


@dataclass(frozen=True)
class RecoveryResult:
    config: StateSpaceConfig
    negative_log_likelihood: float
    success: bool
    message: str


def _center(values: np.ndarray) -> np.ndarray:
    return values - float(values.mean())


def simulate_gaussian_team_state_history(
    team_ids: Sequence[str],
    *,
    config: StateSpaceConfig,
    n_weeks: int,
    seed: int,
) -> tuple[SyntheticWeek, ...]:
    """Generate one-season synthetic observations under the Gaussian model.

    Each week pairs teams randomly, then generates two directed observations per
    game (home offense vs away defense and vice versa). One observation here is
    an aggregate synthetic measurement, not an NFL play. The harness isolates
    persistence/process/observation identification from play-cohort questions.
    """

    teams = tuple(team_ids)
    if len(teams) < 4 or len(teams) % 2:
        raise ValueError("synthetic recovery requires an even number of at least four teams")
    if len(set(teams)) != len(teams):
        raise ValueError("team_ids must be unique")
    if n_weeks < 8:
        raise ValueError("n_weeks must be at least 8")

    rng = np.random.default_rng(seed)
    n = len(teams)
    offense = _center(rng.normal(0.0, config.initial_offense_sd, size=n))
    defense = _center(rng.normal(0.0, config.initial_defense_sd, size=n))
    alpha = float(config.league_intercept_global)
    weeks: list[SyntheticWeek] = []

    for week in range(n_weeks):
        if week:
            offense = _center(
                config.offense_rho * offense
                + rng.normal(0.0, config.offense_process_sd, size=n)
            )
            defense = _center(
                config.defense_rho * defense
                + rng.normal(0.0, config.defense_process_sd, size=n)
            )

        order = rng.permutation(n)
        offenses: list[str] = []
        defenses: list[str] = []
        observations: list[float] = []
        for pair_start in range(0, n, 2):
            a = int(order[pair_start])
            b = int(order[pair_start + 1])
            for offense_idx, defense_idx in ((a, b), (b, a)):
                mean = alpha + offense[offense_idx] - defense[defense_idx]
                value = mean + rng.normal(0.0, config.observation_sd)
                offenses.append(teams[offense_idx])
                defenses.append(teams[defense_idx])
                observations.append(float(value))

        weeks.append(
            SyntheticWeek(
                offenses=tuple(offenses),
                defenses=tuple(defenses),
                observations=np.asarray(observations, dtype=float),
            )
        )

    return tuple(weeks)


def gaussian_prequential_nll(
    team_ids: Sequence[str],
    weeks: Sequence[SyntheticWeek],
    config: StateSpaceConfig,
) -> float:
    """One-step predictive Gaussian negative log likelihood.

    Observations within a frozen week are scored sequentially under the exact
    Gaussian predictive decomposition; no latent transition occurs inside the
    week. A weekly transition occurs before each week after the first.
    """

    if not weeks:
        raise ValueError("at least one synthetic week is required")
    model = GaussianOffenseDefenseFilter(team_ids, config)
    nll = 0.0

    for week_index, batch in enumerate(weeks):
        if week_index:
            model.transition(1)
        for offense, defense, observed in zip(
            batch.offenses, batch.defenses, batch.observations, strict=True
        ):
            mean, state_var = model.matchup_moments(offense, defense)
            predictive_var = state_var + config.observation_sd**2
            if predictive_var <= 0.0 or not np.isfinite(predictive_var):
                return float("inf")
            residual = float(observed - mean)
            nll += 0.5 * (log(2.0 * pi * predictive_var) + residual**2 / predictive_var)
            model.update_game_batch([offense], [defense], [float(observed)])

    return float(nll)


def _config_from_vector(base: StateSpaceConfig, x: np.ndarray) -> StateSpaceConfig:
    return replace(
        base,
        offense_rho=float(x[0]),
        defense_rho=float(x[1]),
        offense_process_sd=float(np.exp(x[2])),
        defense_process_sd=float(np.exp(x[3])),
        observation_sd=float(np.exp(x[4])),
    )


def fit_gaussian_recovery_parameters(
    team_ids: Sequence[str],
    weeks: Sequence[SyntheticWeek],
    *,
    base_config: StateSpaceConfig,
    initial: StateSpaceConfig | None = None,
    maxiter: int = 250,
) -> RecoveryResult:
    """Fit five within-season parameters for synthetic recovery diagnostics.

    Initial/offseason/intercept quantities are deliberately held fixed. The
    diagnostic asks whether the implementation can recover the parameters that
    are most likely to be confounded in real data: offense/defense persistence,
    offense/defense process scale, and observation scale.
    """

    start = initial or base_config
    x0 = np.array(
        [
            start.offense_rho,
            start.defense_rho,
            log(start.offense_process_sd),
            log(start.defense_process_sd),
            log(start.observation_sd),
        ],
        dtype=float,
    )
    bounds = [
        (0.20, 0.999),
        (0.20, 0.999),
        (log(0.002), log(0.50)),
        (log(0.002), log(0.50)),
        (log(0.05), log(3.00)),
    ]

    def objective(x: np.ndarray) -> float:
        candidate = _config_from_vector(base_config, x)
        return gaussian_prequential_nll(team_ids, weeks, candidate)

    result = minimize(
        objective,
        x0,
        method="L-BFGS-B",
        bounds=bounds,
        options={"maxiter": int(maxiter), "ftol": 1e-10},
    )
    fitted = _config_from_vector(base_config, np.asarray(result.x, dtype=float))
    return RecoveryResult(
        config=fitted,
        negative_log_likelihood=float(result.fun),
        success=bool(result.success),
        message=str(result.message),
    )
