import sys,json,hashlib,shutil
from pathlib import Path
from datetime import datetime,timezone
import pandas as pd
repo=Path(__file__).resolve().parent.parent/'BK_availability_audit';sys.path.insert(0,str(repo));base=Path(__file__).resolve().parent;decoded=base/'decoded';out=repo.parent.parent/'outputs/phase3b-expanded-super-bowl-extension'
from ball_knower_v3.canonical.common import normalize_team_series
from ball_knower_v3.modeling.team_state import StateSpaceConfig
from ball_knower_v3.modeling.state_fitting import CandidateSpace,canonical_json
from ball_knower_v3.modeling.export_structural_state import export_table
regular=json.loads((base/'expanded-experiment.json').read_text());rec=next(r for r in json.loads((base/'decoded-source-catalog.json').read_text()) if r['asset_id']==347739173);g=pd.read_parquet(decoded/'2026-01-29-games.parquet');g=g[g.week.eq(22)].copy();kickoff=pd.to_datetime(g.gameday+' '+g.gametime).dt.tz_localize('America/New_York').dt.tz_convert('UTC');fg=g[['game_id','season','week','home_team','away_team']].copy();fg['kickoff']=kickoff
for c in ['home_team','away_team']:fg[c]=normalize_team_series(fg[c])
fg['schedule_known_at']=rec['source_available_at'];fg['schedule_dataset_id']=f"archive:asset:{rec['asset_id']}:sha256:{rec['source_sha256']}";fg['schedule_evidence_id']=rec['metadata_url'];fg['schedule_provenance_class']='historical_source_proven';fg['is_final']=False
origin=pd.DataFrame([dict(season=2025,week=22,as_of='2026-02-03T16:00:00Z')]);assert len(fg)==1 and g[['home_score','away_score']].isna().all().all() and (fg.kickoff>pd.Timestamp(origin.as_of.iloc[0])).all()
spec=dict(schema_version='phase3b_super_bowl_retrospective_extension_v1',experiment_registered_at=pd.Timestamp.now(tz='UTC').isoformat(),candidates=regular['candidates'],seed=13,origins=origin.to_dict('records'),evidence_class='retrospective_historical_source_replay',source_selection_policy=regular['source_selection_policy'],schedule_selection_policy=regular['schedule_selection_policy'],selected_week_versions_sha256=regular['selected_week_versions_sha256'],decoded_source_catalog_sha256=regular['decoded_source_catalog_sha256'],schedule_asset_id=rec['asset_id'],schedule_sha256=rec['source_sha256'],schedule_available_at=rec['source_available_at'],prior_regular_experiment_results_known=True,extension_reason='Schedule feasibility only; candidate family and source selection unchanged; no target outcomes consumed',purpose='Append-only strict Super Bowl structural origin; retrospective development evidence only')
(base/'super-bowl-extension-experiment.json').write_text(json.dumps(spec,indent=2)+'\n');space=CandidateSpace(tuple(StateSpaceConfig(**c) for c in spec['candidates']),experiment_registered_at=spec['experiment_registered_at']);inputs={p.stem:pd.read_parquet(p) for p in (base/'expanded-inputs').glob('*.parquet')};execution=datetime.now(timezone.utc).isoformat();table=export_table(games=inputs['observation_games'],forecast_games=fg,plays=inputs['plays'],availability=inputs['availability'],origins=origin,space=space,output_dir=out,seed=13,replay_execution_at=execution,write_completion_manifest=False);shutil.copy2(base/'super-bowl-extension-experiment.json',out/'experiment.json');fg.to_parquet(out/'forecast_games.parquet',index=False);origin.to_parquet(out/'origins.parquet',index=False)
files={str(p.relative_to(out)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.rglob('*')) if p.is_file()};manifest=dict(schema_version='phase3b_super_bowl_retrospective_extension_bundle_v1',rows=len(table),origins=1,experiment_registered_at=spec['experiment_registered_at'],replay_execution_at=execution,execution_code_commit=json.loads(next((out/'configs').glob('*.json')).read_text())['content']['code']['commit'],files=files,prospective_evidence=False,historical_forecast_existence_proven=False,target_outcomes_scored=False);(out/'manifest.json').write_text(canonical_json(manifest)+'\n');print(manifest);print('table',files['structural_state_forecasts.csv'])
